"""empty message

Revision ID: 87214ddde132
Revises: de5d273c2339
Create Date: 2023-07-12 19:56:57.789099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87214ddde132'
down_revision = 'de5d273c2339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=155), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_image')
    # ### end Alembic commands ###
